from __future__ import annotations

import json
import os
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from html import escape
from pathlib import Path

API = "https://api.github.com"
USERNAME = os.environ.get("GITHUB_REPOSITORY_OWNER", "morg1z")

# PROFILE_STATS_TOKEN is optional, but required if you want TOTAL REPOS
# to include private repositories owned by the account.
TOKEN = os.environ.get("PROFILE_STATS_TOKEN") or os.environ.get("GITHUB_TOKEN", "")
HAS_PRIVATE_TOKEN = bool(os.environ.get("PROFILE_STATS_TOKEN"))


def github_json(url: str):
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": "morg1z-profile-stats",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    if TOKEN:
        headers["Authorization"] = f"Bearer {TOKEN}"

    request = urllib.request.Request(url, headers=headers)
    with urllib.request.urlopen(request, timeout=30) as response:
        return json.load(response)


def paginated(url: str):
    items = []
    page = 1

    while True:
        separator = "&" if "?" in url else "?"
        batch = github_json(f"{url}{separator}per_page=100&page={page}")
        items.extend(batch)

        if len(batch) < 100:
            break

        page += 1

    return items


def get_public_repos(username: str):
    params = urllib.parse.urlencode({
        "type": "owner",
        "sort": "updated",
    })
    return paginated(f"{API}/users/{username}/repos?{params}")


def get_owned_repos_including_private():
    # This endpoint only includes private repositories when PROFILE_STATS_TOKEN
    # has access to them.
    params = urllib.parse.urlencode({
        "visibility": "all",
        "affiliation": "owner",
        "sort": "updated",
    })
    return paginated(f"{API}/user/repos?{params}")


def metric_box(x: int, width: int, label: str, value: str) -> str:
    return f"""
  <rect x="{x}" y="112" width="{width}" height="92" rx="12" fill="#161b22" stroke="#30363d"/>
  <text x="{x + 18}" y="142" fill="#8b949e" font-family="-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif" font-size="14" font-weight="700">{escape(label)}</text>
  <text x="{x + 18}" y="184" fill="#58a6ff" font-family="-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif" font-size="34" font-weight="800">{escape(value)}</text>"""


def main():
    profile = github_json(f"{API}/users/{USERNAME}")
    public_repos_data = get_public_repos(USERNAME)

    public_repos = int(profile.get("public_repos", len(public_repos_data)))
    followers = int(profile.get("followers", 0))
    stars = sum(int(repo.get("stargazers_count", 0)) for repo in public_repos_data)
    forks = sum(int(repo.get("forks_count", 0)) for repo in public_repos_data)

    total_repos = public_repos
    total_label = "TOTAL REPOS"
    privacy_note = "public only — add PROFILE_STATS_TOKEN for private repos"

    if HAS_PRIVATE_TOKEN:
        try:
            owned_repos = get_owned_repos_including_private()
            total_repos = len(owned_repos)
            privacy_note = "includes private repositories"
        except Exception as exc:
            print(f"Could not read private repositories: {exc}")

    updated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" width="960" height="270" viewBox="0 0 960 270" role="img" aria-labelledby="title desc">
  <title id="title">{escape(USERNAME)} GitHub stats</title>
  <desc id="desc">GitHub profile statistics generated by GitHub Actions.</desc>

  <rect width="960" height="270" rx="16" fill="#0d1117" stroke="#30363d"/>

  <text x="32" y="48" fill="#f0f6fc" font-family="-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif" font-size="27" font-weight="800">{escape(USERNAME)} / GitHub stats</text>
  <text x="32" y="78" fill="#8b949e" font-family="-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif" font-size="14">generated locally in this repository</text>

{metric_box(32, 166, "PUBLIC REPOS", str(public_repos))}
{metric_box(214, 166, total_label, str(total_repos))}
{metric_box(396, 166, "FOLLOWERS", str(followers))}
{metric_box(578, 166, "TOTAL STARS", str(stars))}
{metric_box(760, 168, "TOTAL FORKS", str(forks))}

  <text x="32" y="236" fill="#8b949e" font-family="-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif" font-size="12">{escape(privacy_note)}</text>
  <text x="928" y="236" text-anchor="end" fill="#6e7681" font-family="-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif" font-size="12">updated {updated}</text>
</svg>
"""

    output = Path(__file__).with_name("stats.svg")
    output.write_text(svg, encoding="utf-8")
    print(f"Wrote {output}")


if __name__ == "__main__":
    main()
