from __future__ import annotations

import json
import os
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from html import escape
from pathlib import Path

API = "https://api.github.com"
USERNAME = os.environ.get("GITHUB_REPOSITORY_OWNER", "morg1z")
TOKEN = os.environ.get("GITHUB_TOKEN", "")


def github_json(url: str):
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": "morg1z-profile-stats",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    if TOKEN:
        headers["Authorization"] = f"Bearer {TOKEN}"

    request = urllib.request.Request(url, headers=headers)
    with urllib.request.urlopen(request, timeout=30) as response:
        return json.load(response)


def get_all_public_repos(username: str):
    repos = []
    page = 1

    while True:
        params = urllib.parse.urlencode({
            "per_page": 100,
            "page": page,
            "type": "owner",
            "sort": "updated",
        })
        batch = github_json(f"{API}/users/{username}/repos?{params}")
        repos.extend(batch)

        if len(batch) < 100:
            break

        page += 1

    return repos


def metric_box(x: int, width: int, label: str, value: str) -> str:
    return f"""
  <rect x="{x}" y="88" width="{width}" height="76" rx="10" fill="#161b22" stroke="#21262d"/>
  <text x="{x + 14}" y="111" fill="#8b949e" font-family="-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif" font-size="11" font-weight="600">{escape(label)}</text>
  <text x="{x + 14}" y="145" fill="#58a6ff" font-family="-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif" font-size="26" font-weight="700">{escape(value)}</text>"""


def main():
    profile = github_json(f"{API}/users/{USERNAME}")
    repos = get_all_public_repos(USERNAME)

    public_repos = int(profile.get("public_repos", len(repos)))
    followers = int(profile.get("followers", 0))
    stars = sum(int(repo.get("stargazers_count", 0)) for repo in repos)
    forks = sum(int(repo.get("forks_count", 0)) for repo in repos)
    updated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" width="720" height="210" viewBox="0 0 720 210" role="img" aria-labelledby="title desc">
  <title id="title">{escape(USERNAME)} GitHub stats</title>
  <desc id="desc">GitHub profile statistics generated by GitHub Actions.</desc>
  <rect width="720" height="210" rx="14" fill="#0d1117" stroke="#30363d"/>
  <text x="28" y="42" fill="#f0f6fc" font-family="-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif" font-size="22" font-weight="700">{escape(USERNAME)} / GitHub stats</text>
  <text x="28" y="66" fill="#8b949e" font-family="-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif" font-size="12">generated locally in this repository</text>
{metric_box(28, 150, "PUBLIC REPOS", str(public_repos))}
{metric_box(194, 150, "FOLLOWERS", str(followers))}
{metric_box(360, 150, "TOTAL STARS", str(stars))}
{metric_box(526, 166, "TOTAL FORKS", str(forks))}
  <text x="28" y="190" fill="#6e7681" font-family="-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif" font-size="11">updated {updated}</text>
</svg>
"""

    output = Path(__file__).with_name("stats.svg")
    output.write_text(svg, encoding="utf-8")
    print(f"Wrote {output}")


if __name__ == "__main__":
    main()
